[Main]
Foo='Bar'

[Command_options]
Timeout = 10

[Output]
Separator = ': '

[Image]
Type = 'Ascii'
Src = './tux.png'

Background = [0, 0, 0]
Lines = 20
#Palette = '█▓▒░ '
Palette = '$8o:. '
#Palette = '@%#*+=-:. '
#Palette = '@BR*#$PX0woIcv:+!~"., '
#Palette = "$@B%8&WM#*oahkbdpqwmZO0QLCJUYXzcvunxrjft/\\|()1{}[]?-_+~<>i!lI;:,\"^`'. "
Resize = 'contain'

[Info]
#_centered_test_ = ['echo', '1234567890 1234567890 1234567890 0987654321 0987654321 0987654321']
Architecture = ['uname', '-m']

Hardware_OS_Separator = 1
Kernel = ['uname', '-sr']
Operating_System = ['uname', '-o']
Distribution = 'echo "`lsb_release -ds | tr -d \\"` `lsb_release -rs`"'

OS_GUI_Separator = 1
Display_Server = ['pacman', '-Q', 'xorg-server']
Desktop_Environment = 'xfce4-session --version | grep -o "(X.*)" | tr -d "()"'

GUI_Terminal_Separator = 1
Terminal_Emulator = 'echo "QTerminal `qterminal --version 2>/dev/null`"'
Shell = ['fish', '--version']

Extras_Separator = 1
_Colors_ = ['echo', '-e', '\e[1;30;40m▄\e[31;41m▄\e[33;43m▄\e[32;42m▄\e[36;46m▄\e[34;44m▄\e[35;45m▄\e[37;47m▄\e[0m']
