[Main]
Comment=['This is a secondary configuration for testing purposes.',
    'It is based on the work of Marcos Oliveira from Terminal Root.',
    'His implementation of a fetch-like program is available at',
    'https://github.com/terroo/myfetch',
    'and a livestream where he codes it, with commentary is available at',
    'https://youtu.be/2_tnd8g-IMc']

[Command_options]
Timeout = 10

[Output]
Separator = ': '

[Image]
Type='None'

[Info]
_Title = 'echo $USER@$HOSTNAME'
_qtd = 'echo $USER@$HOSTNAME | tr [:print:] -' # Known-bug: parser does not recognize unicode escapes \u2500
#Distro = "cat /proc/version | egrep -o '\\([A-Z][a-z]+ ' | tr -d \\("
Distro = "lsb_release -d | sed 's/.*:\\s*//g'"
OS = ['uname', '-o']
Kernel_Name = ['cat', '/proc/sys/kernel/ostype']
Kernel_Version = ['cat', '/proc/sys/kernel/osrelease']
Uptime = "echo `uptime | awk '{print $3}' | tr -d ,` min"
Shell = "basename $SHELL | sed 's/./\\u&/'"
Resolution = "xrandr | sed -n '1p' | sed 's/.*current.//g;s/,.*//g;s/ //g'"
Desk = "echo $XDG_SESSION_DESKTOP"
Font = "fc-match | sed 's/\\..*//g'"
CPU = "cat /proc/cpuinfo | grep -o 'model name.*' | sed -n 1p | sed 's/.*:.//g;s/(.*)//g'"
RAM = "echo `echo \"\\`cat /proc/meminfo | sed -n 1p | tr -d [A-Za-z:' '\\` / 1000000\" | bc` MB"
Mem_Free = "echo `echo \"scale=2;\\`cat /proc/meminfo | sed -n 2p | tr -d [A-Za-z:' '\\` / 1000000\" | bc` MB"
Architeture = "echo `getconf LONG_BIT`-bit"
Browser_default = "echo `xdg-settings get default-web-browser | sed 's/userapp-//g;s/-.*//g;s/\\..*//g'` | sed 's/./\\u&/'"
